### ISSUE TITLE
Extension doesn't load all.css and all.js — adds unnecessary part to url of assets

### ISSUE THREAD

**Issue by emma-sg** [goldenratio/zeronet-protocol-crx#2]
The extension tries to load `all.css` and `all.js` from `http://1.0.0.127.in-addr.arpa:43110/uimedia/all.css` and `http://1.0.0.127.in-addr.arpa:43110/uimedia/all.js` — should be loading from `http://127.0.0.1:43110/uimedia/all.css` and `http://127.0.0.1:43110/uimedia/all.js`. Changing the settings affects the loading of the iframe, but doesn't change the location that these resources are attempted to be read from.

**Comment by goldenratio** [comment]
need more details, please. Network tab screenshot of your browser will be helpful.
also shouldn't it load resources like,
`http://zero/uimedia/all.css` ?

**Comment by emma-sg** [comment]
![screen shot 2015-06-07 at 5 37 15 pm](https://cloud.githubusercontent.com/assets/5727389/8026215/1fa5a89e-0d3c-11e5-9c05-be3500d176ae.png)

Is this screenshot helpful? 

I'm on OS X 10.10, running Chrome 45 (dev) and 43 (stable). Installed via the Chrome Web Store.

Let me know what other info I can provide.

**Comment by HelloZeroNet** [comment]
The problem is not in the extension. But in zeronet source code: https://github.com/HelloZeroNet/ZeroNet/blob/master/src/Ui/UiRequest.py#L186

Have to find better solution to find out the server's real address.

The problem:
Websocket connect does not works with proxying so, we can't connect to ws://zeronetwork.bit or ws://zero, so we have to connect to ws://[server real address]:43110, the self.env["SERVER_NAME"] should be the server's hostname, but it looks like it does not works well on every platform.

unfortunately the self.env does not includes the server's real ip address:

```
{  
   'SERVER_SOFTWARE':'gevent/1.0 Python/2.7',
   'SCRIPT_NAME':'',
   'REQUEST_METHOD':'GET',
   'PATH_INFO':'http://zero/1EU1tbG9oC1A8jz2ouVwGZyQ5asrNsE4Vr',
   'SERVER_PROTOCOL':'HTTP/1.1',
   'QUERY_STRING':'',
   'REMOTE_ADDR':'127.0.0.1',
   'HTTP_USER_AGENT':'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2414.0 Safari/537.36',
   'SERVER_NAME':'localhost',
   'REMOTE_PORT':'54851',
   'wsgi.url_scheme':'http',
   'SERVER_PORT':'43110',
   'HTTP_PRAGMA':'no-cache',
   'werkzeug.request':   <BaseRequest 'http:   //zero/http://zero/1EU1tbG9oC1A8jz2ouVwGZyQ5asrNsE4Vr'   [  
      GET
   ]   >,
   'wsgi.input':<gevent.pywsgi.Input object at 0x03850510>,
   'HTTP_HOST':'zero',
   'wsgi.multithread':False,
   'HTTP_CACHE_CONTROL':'no-cache',
   'HTTP_ACCEPT':'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
   'wsgi.version':(1,
   0   ),
   'GATEWAY_INTERFACE':'CGI/1.1',
   'wsgi.run_once':False,
   'HTTP_PROXY_CONNECTION':'keep-alive',
   'wsgi.errors':<open file '<stderr>',
   mode 'w' 
at 0x01D2D0D0>,
   'wsgi.multiprocess':False,
   'HTTP_ACCEPT_LANGUAGE':'en-US,en;q=0.8,hu;q=0.6',
   'HTTP_ACCEPT_ENCODING':'gzip, deflate, sdch'
}
```

It would be nice if the extension could pass the server's ip address as http request variable (not sure if its possible).

As workaround we could replace 1.0.0.127.in-addr.arpa to 127.0.0.1 to make it work in OSX.

**Comment by HelloZeroNet** [comment]
@EdenSG I think i found a workaround for the problem, please change the [src/Ui/UiRequest.py](https://github.com/HelloZeroNet/ZeroNet/blob/master/src/Ui/UiRequest.py#L185-L190) file to this (probably needs reidenting with tab because github converts tabs to spaces in comments):

``` python

            if self.isProxyRequest(): # Its a remote proxy request
                if self.env["REMOTE_ADDR"] == "127.0.0.1": # Local client, the server address also should be 127.0.0.1
                    server_url = "http://127.0.0.1:%s" % self.env["SERVER_PORT"]
                else: # Remove client, use SERVER_NAME as servers real address
                    server_url = "http://%s:%s" % (self.env["SERVER_NAME"], self.env["SERVER_PORT"])
                homepage = "http://zero/"+config.homepage
            else: # Use relative path
                server_url = ""
                homepage = "/"+config.homepage
```

if this works then i will submit the patch to the main repo

**Comment by emma-sg** [comment]
@HelloZeroNet No, it doesn't seem to make a difference — the resources are still attempted to be loaded from the same location.

**Comment by HelloZeroNet** [comment]
Then probably your remote_addr is not 127.0.0.1
please try to add a `print self.env["REMOTE_ADDR"]` before `if self.isProxyRequest(): # Its a remote proxy request` line and check your console for reported remote_addr

**Comment by emma-sg** [comment]
It is — I haven't configured any custom settings, but just to be sure, I added the line and it printed `127.0.0.1`.

**Comment by emma-sg** [comment]
Oh wait, it's working now.

I don't know why, but it is. I'll let you know if it stops again, but I'll close this for now.
Thanks!
